/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.codelab.basics.ui.theme

import androidx.compose.ui.graphics.Color

val cardCollapsedBackgroundColor = Color(0xFFFEFFFD)
val cardExpandedBackgroundColor = Color(0xFF94CADF)



val md_theme_light_primary = Color(0xFF1560A5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C38)
val md_theme_light_secondary = Color(0xFF545F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF111C2B)
val md_theme_light_tertiary = Color(0xFF00677E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB5EBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFA2C9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1560A5)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA2C9FF)
val md_theme_dark_onPrimary = Color(0xFF00315B)
val md_theme_dark_primaryContainer = Color(0xFF004881)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_secondary = Color(0xFFBCC7DB)
val md_theme_dark_onSecondary = Color(0xFF263141)
val md_theme_dark_secondaryContainer = Color(0xFF3C4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_theme_dark_tertiary = Color(0xFF5BD5FA)
val md_theme_dark_onTertiary = Color(0xFF003543)
val md_theme_dark_tertiaryContainer = Color(0xFF004E60)
val md_theme_dark_onTertiaryContainer = Color(0xFFB5EBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF1560A5)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA2C9FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF263549)
val darkblue = Color(0xFF263549)
val light_darkblue = Color(0xFF1560A5)
val light_ondarkblue = Color(0xFFFFFFFF)
val light_darkblueContainer = Color(0xFFD3E4FF)
val light_ondarkblueContainer = Color(0xFF001C38)
val dark_darkblue = Color(0xFFA2C9FF)
val dark_ondarkblue = Color(0xFF00315B)
val dark_darkblueContainer = Color(0xFF004881)
val dark_ondarkblueContainer = Color(0xFFD3E4FF)












/*


 val bmd_theme_light_primary = Color(0xFF825500)
val bmd_theme_light_onPrimary = Color(0xFFFFFFFF)
val bmd_theme_light_primaryContainer = Color(0xFFFFDDB3)
val bmd_theme_light_onPrimaryContainer = Color(0xFF291800)
val bmd_theme_light_secondary = Color(0xFF6F5B40)
val bmd_theme_light_onSecondary = Color(0xFFFFFFFF)
val bmd_theme_light_secondaryContainer = Color(0xFFFBDEBC)
val bmd_theme_light_onSecondaryContainer = Color(0xFF271904)
val bmd_theme_light_tertiary = Color(0xFF51643F)
val bmd_theme_light_onTertiary = Color(0xFFFFFFFF)
val bmd_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val bmd_theme_light_onTertiaryContainer = Color(0xFF102004)
val bmd_theme_light_error = Color(0xFFBA1A1A)
val bmd_theme_light_errorContainer = Color(0xFFFFDAD6)
val bmd_theme_light_onError = Color(0xFFFFFFFF)
val bmd_theme_light_onErrorContainer = Color(0xFF410002)
val bmd_theme_light_background = Color(0xFFFFFBFF)
val bmd_theme_light_onBackground = Color(0xFF1F1B16)
val bmd_theme_light_surface = Color(0xFFFFFBFF)
val bmd_theme_light_onSurface = Color(0xFF1F1B16)
val bmd_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val bmd_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val bmd_theme_light_outline = Color(0xFF817567)
val bmd_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val bmd_theme_light_inverseSurface = Color(0xFF34302A)
val bmd_theme_light_inversePrimary = Color(0xFFFFB951)
val bmd_theme_light_shadow = Color(0xFF000000)
val bmd_theme_light_surfaceTint = Color(0xFF825500)
val bmd_theme_light_outlineVariant = Color(0xFFD3C4B4)
val bmd_theme_light_scrim = Color(0xFF000000)

val bmd_theme_dark_primary = Color(0xFFFFB951)
val bmd_theme_dark_onPrimary = Color(0xFF452B00)
val bmd_theme_dark_primaryContainer = Color(0xFF633F00)
val bmd_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val bmd_theme_dark_secondary = Color(0xFFDDC2A1)
val bmd_theme_dark_onSecondary = Color(0xFF3E2D16)
val bmd_theme_dark_secondaryContainer = Color(0xFF56442A)
val bmd_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
val bmd_theme_dark_tertiary = Color(0xFFB8CEA1)
val bmd_theme_dark_onTertiary = Color(0xFF243515)
val bmd_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val bmd_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val bmd_theme_dark_error = Color(0xFFFFB4AB)
val bmd_theme_dark_errorContainer = Color(0xFF93000A)
val bmd_theme_dark_onError = Color(0xFF690005)
val bmd_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val bmd_theme_dark_background = Color(0xFF1F1B16)
val bmd_theme_dark_onBackground = Color(0xFFEAE1D9)
val bmd_theme_dark_surface = Color(0xFF1F1B16)
val bmd_theme_dark_onSurface = Color(0xFFEAE1D9)
val bmd_theme_dark_surfaceVariant = Color(0xFF4F4539)
val bmd_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val bmd_theme_dark_outline = Color(0xFF9C8F80)
val bmd_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val bmd_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val bmd_theme_dark_inversePrimary = Color(0xFF825500)
val bmd_theme_dark_shadow = Color(0xFF000000)
val bmd_theme_dark_surfaceTint = Color(0xFFFFB951)
val bmd_theme_dark_outlineVariant = Color(0xFF4F4539)
val bmd_theme_dark_scrim = Color(0xFF000000)


val seeds = Color(0xFF825500)

//darkblue

val md_theme_light_primary = Color(0xFF00639A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D32)
val md_theme_light_secondary = Color(0xFF51606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
val md_theme_light_tertiary = Color(0xFF68587A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEEDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF221533)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF95CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00639A)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF95CCFF)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004A75)
val md_theme_dark_onPrimaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_secondary = Color(0xFFB9C8DA)
val md_theme_dark_onSecondary = Color(0xFF233240)
val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E4F6)
val md_theme_dark_tertiary = Color(0xFFD3BFE6)
val md_theme_dark_onTertiary = Color(0xFF382A49)
val md_theme_dark_tertiaryContainer = Color(0xFF4F4061)
val md_theme_dark_onTertiaryContainer = Color(0xFFEEDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00639A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF95CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF96CCFF)

//lightbrown
*/


val brownmd_theme_light_primary = Color(0xFFEBE4CD)
val brownmd_theme_light_onPrimary = Color(0xFFFFFFFF)
val brownmd_theme_light_primaryContainer = Color(0xFFF7E467)
val brownmd_theme_light_onPrimaryContainer = Color(0xFF201C00)
val brownmd_theme_light_secondary = Color(0xFF645F41)
val brownmd_theme_light_onSecondary = Color(0xFFFFFFFF)
val brownmd_theme_light_secondaryContainer = Color(0xFFEBE3BD)
val brownmd_theme_light_onSecondaryContainer = Color(0xFF1F1C05)
val brownmd_theme_light_tertiary = Color(0xFF416651)
val brownmd_theme_light_onTertiary = Color(0xFFFFFFFF)
val brownmd_theme_light_tertiaryContainer = Color(0xFFC3ECD1)
val brownmd_theme_light_onTertiaryContainer = Color(0xFF002112)
val brownmd_theme_light_error = Color(0xFFBA1A1A)
val brownmd_theme_light_errorContainer = Color(0xFFFFDAD6)
val brownmd_theme_light_onError = Color(0xFFFFFFFF)
val brownmd_theme_light_onErrorContainer = Color(0xFF410002)
val brownmd_theme_light_background = Color(0xFFF5E9C7)
val brownmd_theme_light_onBackground = Color(0xFF1D1C16)
val brownmd_theme_light_surface = Color(0xFFFFFBFF)
val brownmd_theme_light_onSurface = Color(0xFF1D1C16)
val brownmd_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val brownmd_theme_light_onSurfaceVariant = Color(0xFF4A4739)
val brownmd_theme_light_outline = Color(0xFF7B7768)
val brownmd_theme_light_inverseOnSurface = Color(0xFFF5F0E7)
val brownmd_theme_light_inverseSurface = Color(0xFF32302A)
val brownmd_theme_light_inversePrimary = Color(0xFFDAC84E)
val brownmd_theme_light_shadow = Color(0xFF000000)
val brownmd_theme_light_surfaceTint = Color(0xFF6A5F00)
val brownmd_theme_light_outlineVariant = Color(0xFFCCC6B5)
val brownmd_theme_light_scrim = Color(0xFF000000)
/*
val brownmd_theme_dark_primary = Color(0xFFDAC84E)
val brownmd_theme_dark_onPrimary = Color(0xFFB8A930)
val brownmd_theme_dark_primaryContainer = Color(0xFF504700)
val brownmd_theme_dark_onPrimaryContainer = Color(0xFFF7E467)
val brownmd_theme_dark_secondary = Color(0xFFCFC7A2)
val brownmd_theme_dark_onSecondary = Color(0xFF353117)
val brownmd_theme_dark_secondaryContainer = Color(0xFF4C472B)
val brownmd_theme_dark_onSecondaryContainer = Color(0xFFEBE3BD)
val brownmd_theme_dark_tertiary = Color(0xFFA7D0B6)
val brownmd_theme_dark_onTertiary = Color(0xFF113725)
val brownmd_theme_dark_tertiaryContainer = Color(0xFF294E3A)
val brownmd_theme_dark_onTertiaryContainer = Color(0xFFC3ECD1)
val brownmd_theme_dark_error = Color(0xFFFFB4AB)
val brownmd_theme_dark_errorContainer = Color(0xFF93000A)
val brownmd_theme_dark_onError = Color(0xFF690005)
val brownmd_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val brownmd_theme_dark_background = Color(0xFF1D1C16)
val brownmd_theme_dark_onBackground = Color(0xFFE7E2D9)
val brownmd_theme_dark_surface = Color(0xFF1D1C16)
val brownmd_theme_dark_onSurface = Color(0xFFE7E2D9)
val brownmd_theme_dark_surfaceVariant = Color(0xFF4A4739)
val brownmd_theme_dark_onSurfaceVariant = Color(0xFFCCC6B5)
val brownmd_theme_dark_outline = Color(0xFF959181)
val brownmd_theme_dark_inverseOnSurface = Color(0xFF1D1C16)
val brownmd_theme_dark_inverseSurface = Color(0xFFE7E2D9)
val brownmd_theme_dark_inversePrimary = Color(0xFF6A5F00)
val brownmd_theme_dark_shadow = Color(0xFF000000)
val brownmd_theme_dark_surfaceTint = Color(0xFFDAC84E)
val brownmd_theme_dark_outlineVariant = Color(0xFF4A4739)
val brownmd_theme_dark_scrim = Color(0xFF000000)


val seedss = Color(0xFFFFF8E1)
*/
/*
val md_theme_light_primary = Color(0xFF00639A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D32)
val md_theme_light_secondary = Color(0xFF51606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
val md_theme_light_tertiary = Color(0xFF68587A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEEDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF221533)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF95CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00639A)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF95CCFF)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004A75)
val md_theme_dark_onPrimaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_secondary = Color(0xFFB9C8DA)
val md_theme_dark_onSecondary = Color(0xFF233240)
val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E4F6)
val md_theme_dark_tertiary = Color(0xFFD3BFE6)
val md_theme_dark_onTertiary = Color(0xFF382A49)
val md_theme_dark_tertiaryContainer = Color(0xFF4F4061)
val md_theme_dark_onTertiaryContainer = Color(0xFFEEDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00639A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF95CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF96CCFF)*//*


val mdnew_theme_light_primary = Color(0xFF8E4F00)
val mdnew_theme_light_onPrimary = Color(0xFFFFFFFF)
val mdnew_theme_light_primaryContainer = Color(0xFFFFDCC0)
val mdnew_theme_light_onPrimaryContainer = Color(0xFF2E1600)
val mdnew_theme_light_secondary = Color(0xFF735943)
val mdnew_theme_light_onSecondary = Color(0xFFFFFFFF)
val mdnew_theme_light_secondaryContainer = Color(0xFFFFDCC0)
val mdnew_theme_light_onSecondaryContainer = Color(0xFF291706)
val mdnew_theme_light_tertiary = Color(0xFF5A6238)
val mdnew_theme_light_onTertiary = Color(0xFFFFFFFF)
val mdnew_theme_light_tertiaryContainer = Color(0xFFDFE8B2)
val mdnew_theme_light_onTertiaryContainer = Color(0xFF181E00)
val mdnew_theme_light_error = Color(0xFFBA1A1A)
val mdnew_theme_light_errorContainer = Color(0xFFFFDAD6)
val mdnew_theme_light_onError = Color(0xFFFFFFFF)
val mdnew_theme_light_onErrorContainer = Color(0xFF410002)
val mdnew_theme_light_background = Color(0xFFFFFBFF)
val mdnew_theme_light_onBackground = Color(0xFF201B17)
val mdnew_theme_light_surface = Color(0xFFFFFBFF)
val mdnew_theme_light_onSurface = Color(0xFF201B17)
val mdnew_theme_light_surfaceVariant = Color(0xFFF2DFD1)
val mdnew_theme_light_onSurfaceVariant = Color(0xFF51443A)
val mdnew_theme_light_outline = Color(0xFF837469)
val mdnew_theme_light_inverseOnSurface = Color(0xFFFAEFE8)
val mdnew_theme_light_inverseSurface = Color(0xFF352F2B)
val mdnew_theme_light_inversePrimary = Color(0xFFFFB877)
val mdnew_theme_light_shadow = Color(0xFF000000)
val mdnew_theme_light_surfaceTint = Color(0xFF8E4F00)
val mdnew_theme_light_outlineVariant = Color(0xFFD6C3B6)
val mdnew_theme_light_scrim = Color(0xFF000000)

val mdnew_theme_dark_primary = Color(0xFFFFB877)
val mdnew_theme_dark_onPrimary = Color(0xFF4B2700)
val mdnew_theme_dark_primaryContainer = Color(0xFF6C3A00)
val mdnew_theme_dark_onPrimaryContainer = Color(0xFFFFDCC0)
val mdnew_theme_dark_secondary = Color(0xFFE2C0A5)
val mdnew_theme_dark_onSecondary = Color(0xFF412C19)
val mdnew_theme_dark_secondaryContainer = Color(0xFF5A422D)
val mdnew_theme_dark_onSecondaryContainer = Color(0xFFFFDCC0)
val mdnew_theme_dark_tertiary = Color(0xFFC2CB98)
val mdnew_theme_dark_onTertiary = Color(0xFF2C340E)
val mdnew_theme_dark_tertiaryContainer = Color(0xFF434A23)
val mdnew_theme_dark_onTertiaryContainer = Color(0xFFDFE8B2)
val mdnew_theme_dark_error = Color(0xFFFFB4AB)
val mdnew_theme_dark_errorContainer = Color(0xFF93000A)
val mdnew_theme_dark_onError = Color(0xFF690005)
val mdnew_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val mdnew_theme_dark_background = Color(0xFF201B17)
val mdnew_theme_dark_onBackground = Color(0xFFECE0DA)
val mdnew_theme_dark_surface = Color(0xFF201B17)
val mdnew_theme_dark_onSurface = Color(0xFFECE0DA)
val mdnew_theme_dark_surfaceVariant = Color(0xFF51443A)
val mdnew_theme_dark_onSurfaceVariant = Color(0xFFD6C3B6)
val mdnew_theme_dark_outline = Color(0xFF9E8E82)
val mdnew_theme_dark_inverseOnSurface = Color(0xFF201B17)
val mdnew_theme_dark_inverseSurface = Color(0xFFECE0DA)
val mdnew_theme_dark_inversePrimary = Color(0xFF8E4F00)
val mdnew_theme_dark_shadow = Color(0xFF000000)
val mdnew_theme_dark_surfaceTint = Color(0xFFFFB877)
val mdnew_theme_dark_outlineVariant = Color(0xFF51443A)
val mdnew_theme_dark_scrim = Color(0xFF000000)


val seednew = Color(0xFFFFD1AB)
*/

//
